name: hymnes_adventistes
description: "Receuil de cantiques adventiste en plusieurs langes"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  google_fonts: ^3.0.1
  flutter_riverpod: ^1.0.4
  auto_route: ^7.8.4
  flutter_native_splash: ^2.2.4
  line_icons: ^2.0.1
  argon_buttons_flutter: ^1.1.0
  flutter_easyloading: ^3.0.5
  dio: ^5.4.0
  image_picker: ^0.8.5+3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^1.3.0
  audioplayers: ^1.0.1
  flutter_animate: ^4.4.0
  grouped_list: ^5.1.2
  searchable_listview: ^2.0.1
  hive_listener: ^1.2.1
  flutter_hicons: ^0.0.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.6
  flutter_dotenv: ^5.1.0
  glass_kit: ^3.0.0
  introduction_screen: ^3.1.12
  heroicons: ^0.9.0
  freezed: ^2.1.0+1
  freezed_annotation: ^2.4.1
  path_provider: ^2.1.2
  permission_handler: ^11.1.0
  redacted: ^1.0.11
  hydrated_bloc: ^9.1.3
  uuid: ^3.0.7
  flex_seed_scheme: ^1.4.0
  #awesome_notifications: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  very_good_analysis: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^7.3.2


flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/
    - assets/images/
    - assets/sounds/
    - assets/data/
    - assets/animations/